### ISSUE TITLE
Comments for VnV one:

### ISSUE THREAD

**Issue by MaXiaoye** [deviprasad135/CAS741#12]
Hi Devi,

I am away from linear algebra for years. (I learned it in undergraduate stage) So if my comments are unprofessional then please do not consider and just correct me. I would like to provide more comments from structure perspective. :)

Issue One: 
In System test section, I think it is better to test for different input. Especially test cases for different kinds of invalid inputs. The software should show some error message to user and describe valid input format correspondingly.

Best Regards,
Marshall

**Comment by deviprasad135** [comment]
Thanks for the issue. I have tested for singular matrix for which it will show its a singular matrix no solution. If I give some invalid input the software do not even accept the input.
