### ISSUE TITLE
Comments for VnV two

### ISSUE THREAD

**Issue by MaXiaoye** [deviprasad135/CAS741#13]
Issue two:

For NFR test one, the performance test. I wonder if there will be measurable differences that can reflect obvious speed differences ? Because personally I think result will be calculated and display to user in one second.

And what’s the variable that leads to performance differences. Is the input scale or complexity of algorithm ? I would suggest to make it more specific.

**Comment by deviprasad135** [comment]
Thanks for the issue . I will be noting the time that the software takes to calculate the output for different sizes of input.
