### ISSUE TITLE
Comments for VnV three

### ISSUE THREAD

**Issue by MaXiaoye** [deviprasad135/CAS741#14]
Issue three

About T-12 in unit test section, I wonder if this is the same test case as T-2 and T-6 ?
If not I think it is better to make them clearer and tell reader what is the difference.

And I assume unit test should focus on testing each module, so I would suggest to design unit test case for each module. Maybe this will be done after design of modules are finished :)

**Comment by deviprasad135** [comment]
Thanks for the issue. As you suggested I have modified the unit test section and explained my plan for unit testing.
