### ISSUE TITLE
Comments for VnV five:

### ISSUE THREAD

**Issue by MaXiaoye** [deviprasad135/CAS741#16]
Issue five:

About automated testing and verification tools.

Personally I think these 2 parts in your doc talk about the same thing. I think it is better to tell the reader which programming language you will use to implement this software(I only find the name of IDE). 

And I think you can merge subsection one and two under 4.4 into one because they are both talking about Unit Test Framework in RS.

**Comment by deviprasad135** [comment]
Thanks for the issue. As you suggested I have explicitly stated the programming language i am using and the tools I am using for testing.
