### ISSUE TITLE
SRS Issues

### ISSUE THREAD

**Issue by sccdsyad8663** [deviprasad135/CAS741#2]
Hi Reddy,

Thank you for your SRS document. I was glad to read, but I have a few modest issues to provide. All of them are subjective and just for references.

1.When you define matrix A, m x n is always used, but it seems that multiplication sign used in your Latex document is small letter “x”, which easily makes me confused.

**Comment by sccdsyad8663** [comment]
2. In 4.1, you describe the problem in the project, but the description is just like introducing a software library. You need to explicitly point out what problem you want to solve in your program.

**Comment by deviprasad135** [comment]
Thanks for the issue @sccdsyad8663 . Yes I should have used multiplication sign instead of letter "x".  Now I rectified that mistake.
