### ISSUE TITLE
MG:  Secret and service in Section 6.2.3

### ISSUE THREAD

**Issue by palmerst** [deviprasad135/CAS741#22]
Secrets: Runs the program by harmonizing the different algorithms.
Services: Coordinates and runs the main program.

Since you are writing a library I don't think "runs the program" or "runs the main program" are correct here.  Your library doesn't actually run a program -- it offers an interface that another program can use.

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.
