### ISSUE TITLE
MG:  I don't understand AC5, or how it relates to M4

### ISSUE THREAD

**Issue by palmerst** [deviprasad135/CAS741#24]
AC5: Change of underlying abstract machine.

Based on https://en.wikipedia.org/wiki/Abstract_machine,  I'm not sure this is what you want for AC5.  M4 is really just the exposed interface for your library, so I would think the AC that would go with this would relate to your interface and what it does.

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.
