### ISSUE TITLE
Review MG Comments

### ISSUE THREAD

**Issue by smiths** [deviprasad135/CAS741#25]
Please review the comments in commit 3b91423.  Of particular importance, you should add a matrix module to your design.

**Comment by deviprasad135** [comment]
Hello @smiths ,
I went through your comments in MG Document and found that you have commented to add a matrix module. Can you explain me more explicitly where i should keep my matrix module and what is the use of matrix module? How do I document this module in MIS?

**Comment by smiths** [comment]
A Matrix module will allow you to change the data structure representing your matrix (A).  In the examples you have considered, the matrix A is a small full matrix with no pattern to the entries.  However, in real scientific computing A is large and often has structure that a data structure can take advantage of.  For instance, many matrices are sparse; that is, they have more zero than non-zero entries.  There is no need to store all of the zeros, so new data structures are proposed.  To the external world though, the matrix should still look like a matrix.  Other examples of structure include symmetric matrices, positive definite matrices, triadiagonal matrices etc.

The matrix module will define the Abstract Data Type for matrices.  The set of possible values for the data type will be square matrices with real entries.  The operations will include get and set.  It would also make sense to have addition, subtraction, multiplication etc.  We wouldn't care about efficiency.  The goal is to design for maintainability and change.

In the lectures slides that I presented, the matrix module would be documented in an MIS in the same way as the queue, stack and sequence examples.  You just need to make sure that you document it as a template module, since every object of class MatrixT, will be specified using the same interface.

**Comment by deviprasad135** [comment]
Should I replace input module with matrix module or should I add matrix module separately?

**Comment by smiths** [comment]
The matrix module is a separate module.  The job of your input module can be to populate the objects representing the matrix A, and the matrix (vector) b.

**Comment by deviprasad135** [comment]
It make some sense to me now. Thank you.
