### ISSUE TITLE
MIS Comment #1 : MIS of the Matrix Module

### ISSUE THREAD

**Issue by slimpotatoes** [deviprasad135/CAS741#26]
Hi Devi,

Please find a few comments on the MIS. I hope you will find them useful :).

I will start with the MIS of the Matrix module. I think that "A" and "b" are more referring to the output than really to the functions of the module. I imagine you want to have an access program called "matrix" that transforms a list of n ^2 real numbers into a n x n real matrix. You can have another access program called "vector" that transforms a list of n numbers into a n real vector. 

For that transformation you can use the 2D array data type in which each element of the array is equal to the coefficient of the matrix A[i,j] = aij. You can do the same for the vector B[i]=bi and X[i]=xi. It would help in writing the matriciel expression AX = B somewhere else in the software as a system of equations.  (for each i, sum_j aij xj = bi).

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.
