### ISSUE TITLE
MIS Comment #2: MIS of Input Computing Module

### ISSUE THREAD

**Issue by slimpotatoes** [deviprasad135/CAS741#27]
In the MIS of the Input Computing Module, there is no information of what the module is doing. You have some inputs but nothing is happening for the inputs. Either the module is not used and can be removed or there is something missing. 

I am imagining that this module could be the one writing the values into states variables A, and B using the Matrix module defined in the MIS comment #1.

You can imagine a fonction store taking as a parameter the input from the user and then make the transition for A = matrix(list inputs), B=vector(list inputs) (or output them if you don't want to have A and B as state variable).

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.
