### ISSUE TITLE
MIS Comment #3 : MIS of Gaussian Elimination and MIS of Gauss-Jordan Elimination Modules

### ISSUE THREAD

**Issue by slimpotatoes** [deviprasad135/CAS741#28]
Again a similar comment but I think this one is easy to fix since you have the pseudo code written. A, B and X don't correspond to a function that can be accessed outside of their respective modules, they correspond to inputs and outputs. You would prefer to design a Gaussian_Elim function and a Gauss-Jordan function like:

Gaussian_Elim(A,B) and Gauss-Jordan_Elim(A,B) where A and B are the input. Then depending if X is a state variable or not you can make a transition for X or output X=Gaussian_Elim(A,B) and X=Gauss-Jordan_Elim(A,B). and put your pseudo code.

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.

**Comment by smiths** [comment]
@deviprasad135, you should say what changes you have made to close each of the issues you are closing.  A pointer to the hash code for the commit the closes the issue is also very helpful.
