### ISSUE TITLE
MIS Comment #4 : MIS of LLAES

### ISSUE THREAD

**Issue by slimpotatoes** [deviprasad135/CAS741#29]
The MIS of the LLAES looks a lot like a control module and uses nearly all of the other modules. I think the uses relationship should be visible in the MIS by calling the functions of the modules used. 

So to make the flow smooth, the LLAES should mention the succession of all the functions called (except  if it's a library and it is the role of the user to call them). You could imagine something like that:
- 1) Call the function in the input computing module to record the user inputs A and B
- 2) Call the function to solve AX=B using either option =1 or option =2
- 3) Call the function to ouput the result of X

This way step 1) uses the module IC, step 2) use either the GJE or GE and step 3) use the OC module. For the matrix module, it is difficult to state until the matrix module is fully defined. You can either use or not it depends on your choice in the design.

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.
