### ISSUE TITLE
MIS Comment #5 : Use relationship in modules

### ISSUE THREAD

**Issue by slimpotatoes** [deviprasad135/CAS741#30]
I have the feeling that the relationships between modules in the MIS don't correspond to the ones described in the MG. 

For example in the MG, IC uses nothing and in the MIS IC uses Matrix, GE and GJE. For Matrix, it makes sense since it's a new module you added and can be indeed used by IC. However for GE and GJE, I don't see the connection. GE and GJE are the solvers and don't use any other module (except maybe the Matrix module).

Another example is with OC, in the MG OC is using the Hardware hiding module and in the MIS, OC uses nothing. I think you want OC to keep using the hardware hiding module to display to result to the user.

Last example, the matrix module is using in the MIS GE, GJE and OC. According the comments written in MG, I would imagine the opposite relationship. I think that GE, GJE and IC are potentially using the matrix module (depending on the design choice). 

That's all for my comments. Good luck with the implementation (or with the final document if you already finished it :)).

Alex

**Comment by deviprasad135** [comment]
Thanks for the issue. Your issue was very helpful.
